#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = false
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "nil"
statusline_iseparator = "bar"
buffer_index_type = 4
windows_index_type = 3
enable_tabline_filetype_icon = false
enable_vtatusline_mode = false
statusline_unicode = false
enable_statusline_mode = true
# Enable vim compatible mode, avoid changing origin vim key bindings
# vimcompatible = true
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"
enable_filetree_gitstatus=true
# filetree_direction = "left"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = "default"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'git'

[[layers]]
name = "VersionControl"

[[layers]]
# name = "ctrlp"
name = "denite"

[[layers]]
name = 'github'

[[layers]]
name = 'lang#javascript'
auto_fix = false
enable_flow_syntax=true
format_on_save = true

# [[layers]]
# name = 'lang#c'
# enable_clang_syntax_highlight = true

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
clang_flag = ['-I/user/include']
[layer.clang_std]
cpp = "c++20"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "format"

# [[layers]]
# name = "gtags"
# gtagslabel = "ctags"



[[custom_plugins]]
name = 'SirVer/ultisnips'
merged = false

[[custom_plugins]]
name = 'lilydjwg/colorizer'
merged = false

[[custom_plugins]]
name = 'Chiel92/vim-autoformat'
merged = false

# [[custom_plugins]]
# repo = 'vimwiki/vimwiki'
# merged = false
#
# [[custom_plugins]]
# repo ='neoclide/coc.nvim'
# rev = 'release'
# merged = false

